server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: ms-SensorDataCollector
              uri: lb://SERVICIO-SENSOR
              predicates:
                - Path=/api/sensor-readings/**
              filters:
                - StripPrefix=0
            - id: ms-notificaciones
              uri: lb://SERVICIO-NOTIFICACIONES
              predicates:
                - Path=/notificaciones/**
              filters:
                - StripPrefix=0
eureka:
    client:
      service-url:
          defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
          exposure:
              include: '*'
    endpoint:
        health:
          show-details: always